pipeline {
    agent any

    //environment {
       // WEBEX_ROOM = '' // Room: CICD Notifications
        //WEBEX_CREDS = ''
    //}

    stages {
        //stage("Clone Git Repo"){
            //steps {
                //echo 'Cloning Git Repos'
            //    git branch: 'master', credentialsId:'93f1c9db-b770-40b9-a984-662daeb8dae8', url: 'https://wwwin-github.cisco.com/bac-demo/aci-add-epg.git'
            //}
        //}
       
        stage("deploy"){
            steps {
                echo 'Deploying the application....'
                ansibleTower inventory: 'ACI', jobTemplate: 'ACI2', jobType: 'run', throwExceptionWhenFail: false, towerCredentialsId: 'a284a628-688e-4055-ad06-74b5f059f2c9', towerLogLevel: 'false', towerServer: 'AWX_demo'
            
            }
        }
    }
}

